blog/urls.py
from django.urls import path



app_name = 'blog'


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('words/', views.words, name='words'),
    path('notes/', views.notes, name='notes'),
    path('about/', views.about, name='about'),
]

cart/urls.py
from django.urls import path


app_name = 'cart'

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/add/', views.add, name='add'),
    path('clear/', views.clear, name='clear'),
    path('purchase/', views.purchase, name='purchase'),
]

dgauth/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from movies.models import Movie


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    total = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id) + ' - ' + self.user.username
    
    
class Item(models.Model):
    id = models.AutoField(primary_key=True)
    price = models.IntegerField()
    quantity = models.IntegerField()
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
        
    def __str__(self):
        return str(self.id) + ' - ' + self.movie.name

cart/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from movies.models import Movie
from .utils import calculate_cart_total
from .models import Order, Item
from django.contrib.auth.decorators import login_required


def add(request, id):
    get_object_or_404(Movie, id=id)
    cart = request.session.get('cart', {})
    cart[id] = request.POST['quantity']
    request.session['cart'] = cart
    return redirect('cart:index')




def index(request):
    cart_total = 0
    movies_in_cart = []
    cart = request.session.get('cart', {})
    movie_ids = list(cart.keys())
    if (movie_ids != []):
        movies_in_cart = Movie.objects.filter(id__in=movie_ids)
        cart_total = calculate_cart_total(cart, movies_in_cart)
    ctx = {}
    ctx['title'] = 'Cart'
    ctx['movies_in_cart'] = movies_in_cart
    ctx['cart_total'] = cart_total
    return render(request, 'cart/index.html', ctx)



def clear(request):
    request.session['cart'] = {}
    return redirect('cart:index')



@login_required
def purchase(request):
    cart = request.session.get('cart', {})
    movie_ids = list(cart.keys())
    if (movie_ids == []):
        return redirect('cart:index')
    movies_in_cart = Movie.objects.filter(id__in=movie_ids)
    cart_total = calculate_cart_total(cart, movies_in_cart)
    order = Order()
    order.user = request.user
    order.total = cart_total
    order.save()
    for movie in movies_in_cart:
        item = Item()
        item.movie = movie
        item.price = movie.price
        item.order = order
        item.quantity = cart[str(movie.id)]
        item.save()
        
    request.session['cart'] = {}
    ctx = {}
    ctx['title'] = 'Purchase confirmation'
    ctx['order_id'] = order.id
    return render(request, 'cart/purchase.html', ctx)

cart/templates/cart/index.html
{% extends "home/base.html" %}




{% block content %}
{% load static %}
{% load cart_filters %}

    <div class="p-3">
        <div class="container">
            <div class="row mt-3">
                <div class="col mx-auto mb-3">
                    <h2>Shoping Cart</h2>
                    <hr>
                </div>
            </div>
            <div class="row m-1">
                <table class="table table-bordered table-stripped text-center">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for movie in movies_in_cart %}
                            <tr>
                                <td>{{ movie.id }}</td>
                                <td>{{ movie.name }}</td>
                                <td>{{ movie.price }}</td>
                                <td>{{ request.session.cart|get_quantity:movie.id }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="text-end">
                    <a href="" class="btn btn-outline-secondary mb-2">
                        <b>Total to pay:</b> ${{ cart_total }}
                    </a>
                    {% if movies_in_cart|length > 0 %}
                    <a href="{% url "cart:purchase" %}" class="btn btn-dark text-white mb-2">Purchase</a>
                    <a href="{% url "cart:clear" %}">
                        <button class="btn btn-danger mb-2">
                            Remove all movies from Cart
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

cart/templates/cart/purchase.html
{% extends "home/base.html" %}

{% block content %}
{% load static %}

    <div class="p-3">
        <div class="container">
            <div class="row mt-3">
                <div class="col mx-auto mb-3">
                    <h2>Purchase Completed</h2>
                    <hr>
                    <p>
                        Congratulations, purchase completed. Order number is: <b> #{{ order_id }}</b>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}