accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'


urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('orders/', views.orders, name='orders'),
]

blog/urls.py
from django.urls import path



app_name = 'blog'


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('words/', views.words, name='words'),
    path('notes/', views.notes, name='notes'),
    path('about/', views.about, name='about'),
]

dgauth/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

app_name = 'home'
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

home/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    title = 'Movies Store'
    ctx = {
        'title': title,
    }
    return render(request, 'home/index.html', ctx)





def about(request):
    
    title = 'About'
    ctx = {
        'title': title,
    }
    return render(request, 'home/about.html')

home/templates/home/about.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

    <div class="p-3">
        <div class="row mt-3">
            <div class="col-md-6 mx-auto mb-3">
                <h2>About</h2>
                <hr>
                <p>
                    At Movies Store, we offer a vast digital library
                    that spans across genres, ensuring there's
                    something for every movie lover. Browse our
                    extensive collection of films, including the
                    latest releases, timeless classics, and hidden
                    gems. With just a few clicks, you can rent or
                    purchase your favorite titles and instantly
                    stream them in high-definition quality.
                </p>
                <p>
                    Discover the convenience of our digital platform,
                    where you have the flexibility to watch movies
                    on your preferred device, whether it's a smart
                    TV, tablet, or smartphone. With our intuitive search and recommendation features, finding your
                    next movie night pick has never been easier.
                </p>
            </div>
            <div class="col-md-6 mx-auto mb-3 tetx-center">
                <img src="{% static 'assets/img/about.jpg' %}" alt="about">
            </div>
        </div>
    </div>
{% endblock content %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body>
    {% comment %} Header {% endcomment %}
    <nav class="p-3 navbar navbar-dark bg-dark navbar-expand-lg">
        <div class="container">
            <a href="{% url "home:index" %}" class="navbar-brand">
                <img src="{% static 'assets/img/logo.png' %}" alt="logo" height="40">
            </a>
            <button class="navbar-toggler" 
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup"
                aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ms-auto navbar-ml">
                    <a href="{% url "home:about" %}" class="nav-link">About</a>
                    <a href="{% url "blog:index" %}" class="nav-link">Blog</a>
                    <a href="{% url "movies:index" %}" class="nav-link">Movies</a>
                    <a href="{% url "cart:index" %}" class="nav-link">Cart</a>
                    <div class="vr bg-white mx-2 d-done d-lg-block"></div>
                    {% if user.is_authenticated %}
                        <a href="{% url "accounts:orders" %}" class="nav-link">Orders</a>
                        <a href="{% url "accounts:logout" %}" class="nav-link">
                        Logout ({{ user.username }})
                        </a>
                    {% else %}
                        <a href="{% url "accounts:login" %}" class="nav-link">Login</a>
                        <a href="{% url "accounts:signup" %}" class="nav-link">
                        Sign Up
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    {% comment %} Header {% endcomment %}
    {% block content %}
    
    {% endblock content %}

    {% comment %} Footer {% endcomment %}
    <section class="p-3 ms-footer d-none d-md-block">
        <div class="container">
            <div class="row mt-3 text-white">
                <div class="col-md-6 col-lg-6 col-xl-6 mx-auto mb-4">
                    <b>MOVIES STORE</b>
                    <hr>
                    <p>Welcome to Movies Store, your premier online destination for a cinematic adventure like no other! Dive into  the world of movies from the comfort of your own home with our user-friendly and immersive online movie store.
                    </p>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                    <b>LINKS</b>
                    <hr>
                    <p><a href="{% url "home:about" %}" class="nav-link">About</a></p>
                </div>
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mb-4">
                    <b>CONTACT</b>
                    <hr>
                    <p>
                        <i class="fas fa-home me-2"></i>
                        1540 Vestby, Norway
                    </p>
                    <p>
                        <i class="fas fa-envelope me-2"></i>
                        info@moviestore.com
                    </p>
                    <p>
                        <i class="fas fa-phone me-2"></i>
                        +47 555 77 888
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section class="p-3 ms-footer-bottom bg-dark">
        <div class="container d-flex justify-content-between">
            <div class="me-5 text-white">
                <span>DESIGNED BY 
                    <a href="#" target="_blank">John Oakshield</a> 
                </span>
            </div>
            <div class="text-white"><span>©  Copyright - 2024</span></div>
        </div>
    </section>
    {% comment %} Footer {% endcomment %}
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

home/templates/home/index.html
{% extends "home/base.html" %}
{% load static %}


{% block content %}

    <header class="masterhead bg-index text-white text-center py-4">
        <div class="container dflex align-items-center flex-column pt-2">
            <h2>Movie Store</h2>
            <p>Your Ticket to Unlimited Etrtainment</p>
        </div>
    </header>

    <div class="p-3">
        <div class="container">
            <div class="row mt-3">
                <div class="col mx-auto text-center mb-3">
                    <h4>Welcome to the best movie store!</h4>
                </div>
            </div>
        </div>
    </div>



{% endblock content %}c