blog/urls.py
from django.urls import path



app_name = 'blog'


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('words/', views.words, name='words'),
    path('notes/', views.notes, name='notes'),
    path('about/', views.about, name='about'),
]

cart/urls.py
from django.urls import path


app_name = 'cart'

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/add/', views.add, name='add'),
    path('clear/', views.clear, name='clear'),
    path('purchase/', views.purchase, name='purchase'),
]

dgauth/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.show, name='show'),
    path('<int:id>/review/create/', views.create_review, name='create_review'),
    path('<int:id>/review/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('<int:id>/review/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

movies/models.py
from django.db import models
from django.contrib.auth.models import User



class Movie(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='movie_images/')
    
    def __str__(self):
        return str(self.id) + ' - ' + self.name
    
    
    

class Review(models.Model):
    id = models.AutoField(primary_key=True)
    comment = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id) + ' - ' + self.movie.name

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required


from .models import Movie, Review

def index(request):
    
    title = 'Movies'
    search_term = request.GET.get('search')
    if search_term:
        movies = Movie.objects.filter(name__icontains=search_term)
    else:
        movies = Movie.objects.all()
        
    #movies = Movie.objects.all()
    ctx = {
        'title': title,
        'movies': movies,
    }
    
    return render(request, 'movies/index.html', ctx)


def show(request, id):
    movie = Movie.objects.get(id=id)
    reviews = Review.objects.filter(movie=movie)

    ctx = {
        'movie': movie,
        'reviews': reviews,
    }
    
    return render(request, 'movies/show.html', ctx)


@login_required
def create_review(request, id):
    if request.method == 'POST' and request.POST['comment'] != '':
        movie = Movie.objects.get(id=id)
        review = Review()
        review.comment = request.POST['comment']
        review.movie = movie
        review.user = request.user
        review.save()
        return redirect('movies:show', id=id)
    else:
        return redirect('movies:show', id=id)
    
@login_required
def edit_review(request, id, review_id):
    review = get_object_or_404(Review, id=review_id)
    if request.user != review.user:
        return redirect('movies:show', id=id)
    if request.method =='GET':
        ctx = {}
        ctx['title'] = 'Edit Review'
        ctx['review'] = review
        return render(request, 'movies/edit_review.html', ctx)
    elif request.method =='POST' and request.POST['comment'] != '':
        review = Review.objects.get(id=review_id)
        review.comment = request.POST['comment']
        review.save()
        return redirect('movies:show', id=id)
    else:
        return redirect('movies:show', id=id)
    
    
@login_required
def delete_review(request, id, review_id):
    review = get_object_or_404(Review, id=review_id, user=request.user)
    review.delete()
    return redirect('movies:show', id=id)

movies/templates/movies/edit_review.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

    <div class="p-3">
        <div class="container">
            <div class="row mt-3">
                <div class="col mx-auto mb-3">
                    <h2>Edit Review</h2>
                    <hr>
                    <form method="POST">
                        {% csrf_token %}
                        <p>
                            <label for="comment">Comment:</label>
                            <textarea name="comment" required id="comment" class="form-control">
                                {{ review.comment }}
                            </textarea>
                        </p>
                        <div class="text-start">
                            <button class="btn bg-dark text-white" type="submit">
                                Edit Review
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

movies/templates/movies/index.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
    <div class="p-3">
        <div class="container">
            <div class="row mt-3">
                <h2>List of Movies</h2>
                <hr>
                <p class="card-text">
                    <form method="get">
                        <div class="row">
                            <div class="col-auto">
                                <div class="input-group col-auto">
                                    <div class="input-group-text">Search</div>
                                    <input type="text" class="form-control" name="search">
                                </div>
                            </div>
                            <div class="col-auto">
                                <button class="btn bg-dark text-white" type="submit">Search</button>
                            </div>
                        </div>
                    </form>
                </p>
            </div>
        </div>

        <div class="row">
            {% for movie in movies %}

                <div class="col-md-4 col-lg-3 mb-2">
                    <div class="p-2 card align-items-center pt-4">

                        <img src="{{ movie.image.url }}"
                        class="card-img-top rounded img-card-200" >

                        <div class="card-body text-center">
                            <a href="{% url "movies:show" id=movie.id %}">
                                {{ movie.name}}
                            </a>
                        
                        </div>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock content %}

movies/templates/movies/show.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

    <div class="p-3">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-6 mx-auto mb-3">
                    <h2>{{ movie.name }}</h2>
                    <hr>
                    <p>
                        <b>Description:</b>{{ movie.description }}
                    </p>
                    <p>
                        <b>Price:</b> $ {{ movie.price }}
                    </p>
                    {% comment %} Cart  {% endcomment %}
                    <p class="card-text">
                        <form method="POST" action="{% url "cart:add" id=movie.id %}">
                            <div class="row">
                                {% csrf_token %}
                                <div class="col-auto">
                                    <div class="input-group col-auto">
                                        <div class="input-group-text">
                                            Quantity
                                        </div>
                                        <input type="number" min="1" max="10" name="quantity" value="1" class="form-control quantity-input">
                                    </div>
                                </div>
                                <div class="col-auto">
                                    <button class="btn bg-dark text-white" type="submit">Add to cart</button>
                                </div>
                            </div>
                        </form>
                    </p>

                    {% comment %} REVIEWS {% endcomment %}
                    <h2>Reviews</h2>
                    <hr><ul class="list-group">
                        {% for review in reviews %}
                        
                        <li class="list-group-item pb-3 pt-3">
                            <h5 class="card-title">
                                Review by {{ user.username }}
                            </h5>
                            <h6 class="card-subtitle mb-2 text-muted">
                                {{ review.date }}
                            </h6>
                            <p class="card-text">{{ review.comment }}</p>
                            {% if user.is_authenticated and user == review.user %}
                                <a href="{% url "movies:edit_review" id=movie.id review_id=review.id  %}" class="btn btn-primary">
                                    Edit
                                </a>
                                <a href="{% url "movies:delete_review" id=movie.id review_id=review.id %}" class="btn btn-danger">
                                    Delete
                                </a>
                            {% endif %}
                        </li>{% endfor %}
                    </ul>


                    {% if user.is_authenticated %}
                        <div class="row justify-content-center">
                            <div class="col-12">
                                <div class="card shadow p-3 mb-4 rounded">
                                    <div class="card-body">
                                        <b class="text-started">
                                            Create a review
                                        </b>
                                        <br>
                                        <form method="POST" action="{% url "movies:create_review" id=movie.id %}">
                                            {% csrf_token %}
                                            <p>
                                                <label for="comment">Comment:</label>
                                                <textarea name="comment" required id="comment" class="form-control"></textarea>
                                            </p>
                                            <div class="text-center">
                                                <button type="submit" class="btn bg-dark text-white">
                                                    Add Review
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                    {% endif %}
                </div>
                <div class="col-md-6 mx-auto mb-3 text-center">
                    <img src="{{ movie.image.url }}" class="rounded img-card-400">
                </div>
            </div>
        </div>
    </div>


{% endblock content %}