blog/urls.py
from django.urls import path



app_name = 'blog'


from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('words/', views.words, name='words'),
    path('notes/', views.notes, name='notes'),
    path('about/', views.about, name='about'),
]

dgauth/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('movies/', include('movies.urls', namespace='movies')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('blog/', include('blog.urls', namespace='blog')),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    
    return render(request, 'blog/index.html')


def words(request):
    
    return render(request, 'blog/words.html')


def notes(request):
    
    return render(request, 'blog/notes.html')


def about(request):
    
    return render(request, 'blog/about.html')

blog/templates/blog/about.html
{% extends "blog/blog_base.html" %}
{% load static %}


{% block content %}

    <h1>
        About Deli Greece.
    </h1>

    From Ancient times Greece were famous for the products of the land, the ceramics and marble, the wine and honey. THe climate and the landscape of Greece offers unique opportunity for various areas with microclimate that lead to different taste of one and the same fruit or wine. White beans taste not the just the same. Great importance plays the soil and climate, humidity and elevation. Fruits from Edessa and Veria areas are different from the fruits of Pelopones as well as the vegetabes of Crete have different taste.

    All this lead to the varieties of taste in Greek food, even when it comes to the same dish. Lamb meat from Olympos mountain is different than the one from Attica region. 

    Oregano and many other herbs that Greek kitchen is so famous about, has differend odour and taste from hill to hill, mountain to mountain.

    Everywhere Greek farmers are working in family farms, generation after generation, always trying to keep the heigh quality and traditions of the local produce. 

    Deli Greece is a portal that aim to introduce the producers and their quality products.
    Here you can get to know the person behind the honey yo buy or the home-made pasta. The beans and the dry fruits are not any more just a package, now you will know who is the producer, where does the product comes from.

    Deli Greece does not participate in purchasing the products. It is strictly between you, the customer, and the producer. Our mission is to create possibility for purchasing good product in reasonabe price with the guarantee of the producers themselves.

    Deli Greece will not be the judge of the products on the portal. Customers are the best judges. 
    In order to write comments about products, customers must register. 
    
    Deli Greece does not have any possibility of controlling the accuracy of informations provided by producers. Neither the responsibility for any financial dispute between the seller and buyer. 

    
    Comments with inapropriate content will be removed and the user blocked for further actions.
    

{% endblock content %}

blog/templates/blog/blog_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
</head>
<body>
    
    <header>
        <a href="{% url "home:index" %}">Movies</a>
        <a href="{% url "blog:index" %}">Blog</a>
        <a href="{% url "blog:words" %}">Words</a>
        <a href="{% url "blog:notes" %}">Notes</a>
        <a href="{% url "blog:about" %}">About</a>
    </header>
    {% block content %}

    {% endblock content %}
    
</body>
</html>

blog/templates/blog/index.html
{% extends "blog/blog_base.html" %}
{% load static %}

<div class="container">
{% block content %}


    
    <h1>
        Delightful Greece Blog.
    </h1>
<p>
    Blog about the beauty of Greece. The possibilities and the hopes of Greek people. What we can become in this land given to us by Devine Providence.

    Deli Greece is about giving possibility to the Greek Producer to reach as many people as possible directly. The visitor has the possibility to see variaety of products, to get to know the producer and the information of purchasing the products.
</p>
<p>
    Blogging is a powerful marketing tool. It is a great way to attract potential customers to a website. But no matter how perfect your grammar or interesting your topic is, if no one reads it, then it is just as if it was never there at all. So, it is vital that you make your posts engaging enough to hook your readers and respond to your call-to-action. This is when your copywriter side will come in handy.
</p>

<h1>
    The 4Us Formula
</h1>
<p>
   
<br>
 <b>Useful</b> - If your article has no value to the reader, then they will not read it. Make sure that you write a topic that offers something of great value or targets their pain points. Make your reader realize that your copy provides a solution to their problem or answers their question. What is it that your reader is going to gain by reading your text? Always bear in mind the <b>WIIFM (Whats In It For Me)</b> rule, at every moment and with every hoop you make them go through.
<br>
 <b>Unique</b> - While your topic may be similar to several other blogs on the internet, you can still make your posts stand out and be different by adding a little personality, humor, or something that can arouse interest. Surprise them, pique their interest, share a piece of information they never heard of before.
<br>
<b>Urgency</b> - Create a blog post with a sense of urgency. Your copy should be compelling enough to encourage them to act after reading it. Motivate your reader and convince them that time is of the essence and that they should act now.
<br>
<b>Ultra</b>-Specific - Avoid using vague topics. Be specific and narrow down your topic[…]

</p>

<h1>The AIDA Formula</h1>

<p>
    <b>Attention</b> - Catchy, and attention-grabbing headlines. Your entire content will be useless if you fail to hook your potential customer from your headline. Don’t take for granted the power of a well-crafted headline.
<br>
<b>Interest</b> - Arouse your reader’s interest by writing something relatable to their problems or experiences. From opening to the last sentence, you have to keep the momentum going. Keep them wanting for more. Your post should exude with energy that the reader is motivated to read on. Deliver on the promise you made on your headline so they will keep coming back.
<br>
<b>Desire</b> - Make your target audience want to read your article and crave for more.  Tap into their emotions and connect with their feelings. Make them want what you are offering or do what you want them to do. Depending on your goal for your post, it should be convincing enough to want what you are pitching. Again, the benefit factor will be all that matters in the end.  
<br>
<b>Action</b> - Include a call-to-action on your post. It can be as simple as asking a question that will prompt your readers to comment or participate in a discussion. Engage your reader. You have to[…]


</p>

<h1>The Landing Page</h1>
<p>
   

    It is a stand-alone web page created specifically for marketing and sales intentions. When your prospective customer clicks on your ad or link, this where you will send them. Typically to generate leads by collecting their names and email, or get the sales right then and there! It should be simple and clutter-free. There are limited navigation buttons or links, which is what makes it different from a basic home page. A website can have many different versions of a sales letter.
Landing pages usually use a lead bait to capture your visitor’s information such as a free e-book they give away in exchange for the email.
<br>
<b>Why a Landing Page?</b><br>
The landing page has a single purpose and objective. Convert your visitor into a lead, or make the sale, or any other call to action. They tend to convert more than a homepage because they target a specific audience.
A Homepage is generic and cluttered with links and unnecessary information that your targeted audience won’t need. Sending them to your home page will only confuse and disappoint your potential lead because it does not contain the information they need to complete your Call-To-Action.

<br>

<b>Be Clear and Concise</b><br>
Be brief and as concise as possible. Do not flood your page with vague and unnecessary information. Your instructions should be clear as well. It will not help your prospect see the value of your offer if you are making them guess on the next steps to take. Worse, they might ultimately abandon your landing page.

<br>
<b>Limited Navigation</b><br>
A good landing page should have limited to no navigation at all. They should be kept to just one page and don’t make them exit and enter another page. This will only distract and negatively impacts the visitor’s experience. The only time that you will lead your visitor to another page or link is when you are taking them to your CTA.

<br>
<b>One Goal</b><br>
<i>Your landing page should only have one goal.</i>  Including one too many call-to-actions on your landing page will rob each other’s conversion. It is better to create another landing page for your other conversion goal.


</p>


    <hr>
    <i>
        ***Excerpts From
        The Ultimate Copywriting Guide for Beginners to Advanced
        Neil Hoechlin
        This material may be protected by copyright.
    </i>
    


{% endblock content %}
</div>

blog/templates/blog/notes.html
{% extends "blog/blog_base.html" %}

{% load static %}

{% block content %}
<div class="container">

    <h1>Stategy</h1>
    <p>
      

This new opportunity is the key to their
desire and it’s only attainable through my new
mechanism.
That’s your mission. Write it down.
<br>
As you can see, you can break the one belief
down into three main elements: the new opportunity,
your prospect’s desire, and the new mechanism. Let’s
dig deeper into each one.
<br>
The new opportunity is what makes your idea
unique, your unique selling proposition (USP). If you
don’t have one, your idea is worthless.
    </p>

    <p>
      A fresh chance, a brand-new possibility of success where only disappointment has resulted before.
    </p>

    <p>
      <b>
        The new opportunity reveals WHAT is unique about your solution, the new mechanism reveals HOW it works. 
      </b>
      <p>
        <i>
          Once you know your new opportunity, your customer’s desire, and your new mechanism, you’re ready to write down your one belief.
        </i>
      </p>
    </p>
    <p>
      <h2>Personal notice</h2>
      <p>
        Everybody have a desire for high quality products. Everybody want to trust the origins and production. The best way is to fulfill your desire is to get to know the producer of the products you desire and to have them delievered by the producer. This is the only way that you will know what you buy and whom you buy it from. 
      </p>


      <p class="greek">
        <p class="greek-center">
          Θελετε να εχετε προιοντα υγιεινα και ποιοτικα στο τραπεζι σας; <br>

          Θελετε να γνωριζετε την προελευση των προιοντων; <br>
  
          Θελετε να γνωριζετε τον ανθρωπο η τους ανθρωπους που με αγαπη δημιουργησαν το προιον που επιθυμειτε; <br>
  
        </p>
        
        Καλω ηρθατε στον ιστοτοπο Deli Greece. Ενας χωρος οπου θα βρειτε υγiεινα και ποιοτικα προιοντα, θα γνωρισετε τους παραγωγους και την προελευση των προιοντων.
        <br>

        Ολοι αναζητουμε προιοντα υψηλης ποιοτητας. Η σωστη διατροφη ειναι μια βασικη προυποθεση για την σωστη υγεια για να ανταπεξελθουμε στις καθημερινες απαιτησεις. <br>
         Θελουμε να εμπιστευομαστε την προελευση και την παραγωγη των προιοντων που αγοραζουμε. <br>
          Ο καλυτερος τροπος να ικανοποιησουμε την επιθυμια μας ειναι να γνωρισουμε τον παραγωγο, τον κατασκευαστη του προιοντος που θελουμε. Ειναι ο μονος τροπος να γνωριζουμε τι αγοραζουμε και απο ποιον.
        <br>

        Γοητευτικη Ελλαδα - Delightful Greece εινα ο ιστοτοπος που παρουσιαζει τον παραγωγο και τα προιοντα της παραγωγης στον επισκεπτη. 
        
        <br>

        Σας προσφερei την ευκαιρια να γνωρισεται του ανθρωπους που με μερακι και μοχθο σας προσφερουν τα προιοντα τους στις καλυτερες τιμες της αγορας και με μια μοναδικη εγγυηση, την εμπιστοσυνη στον παραγωγου. <br>
        Δεν ειναι ενας ακομα ιστοτοπος με προιοντα αλλα η δημιουργια μιας σχεσης που θα σας προσφερει προιοντα ποιοτητας που τοσο αναζητατε στη ζωη σας. 
      
      </p>
    </p>


      <section>
        <h2>What's in it for me?</h2>
        <p>
          What the visitor and the producer gain from Deli Greece.
        </p>
      </section>
    <p>
      Ultimate Goal of Deli Greece is to increase the amount of producers and visitors signed and to keep high percentage of visitors on email list. 

        It is to attract the interest of more producers, not only farmers but also of those of smaller or bigger workshops in order to promote their products.

        The ultimate goal is the marketing promotion and consulting of the brand.
        (Brand can be anything form beans and honey to t-shirts and shows and hotels.)

        How do we see the product?
        The product have to be presented on the page in a attractive way, with key words describing the product and prossibility for further information.
        The price and purchasing details must be clear and consise. 
        Contact information of the producer (only registered producers can publish their products) must be detailed and clear. 


        <h2>
            This new opportunity is the key to their desire and it’s only attainable through my new mechanism.
        </h2>
        <p>
            What is the new opportunity? <br>
            It is the promotion of the product throught the pages of Deli Greece.
            What is their desire? It is to get more customers and sell more of the product. 
            Deli Greece is providing the unique possibility of promoting their product in order to increase sales.
        </p>
    </p>
    <p>
        Strategy is a style of thinking, a conscious and deliberate process, an intensive implementation system, the science of ensuring future success. <br>—Pete Johnson, British businessman

      </p>

      <hr>
      <p>
        “If I had asked people what they wanted, they would have said faster horses. <br>—Henry Ford, founder, Ford Motor Company”

      </p>
      <hr>
      <p>
        It must be borne in mind that the tragedy in life doesn’t lie in not reaching your goal. The tragedy lies in having no goal to reach. . . .It is not a disgrace not to reach the stars, but it is a disgrace to have no stars to reach for. <b> Not failure, but low aim is sin.</b> <br>
        —Benjamin E. Mays, minister, educator, scholar, social activist.
      </p>
      <hr>
      <p>
        “One of the main obstacles to thinking big is the inability to outgrow your environment.”

      </p>
      <p>
        “Many entrepreneurs lack the motivation to pursue big ideas.”

      </p>

      <p>
      
        When you write a sales letter, you also must have a Commander’s Intent. And that’s exactly what “the one belief” is. It describes the ultimate goal of the sales letter.
      </p>

      <p>
        A producer will pay a small amount for including their product in newsletters.
        With information about proce and purchasing alternatives the the producer will provide in details.
      </p>

      <p>
        1. Make Haste slowly 2. Strong mind, strong body 3.struggle makes you stronger 4. Love fate 5. Know possibilities, Prepare for the worst 6.character is fate 7. Remember you are mortal.
      </p>

      <hr>
      <section>
        <h1>Questions</h1>

        <div class="question">
          <h2>How is this different from everythong else I've seen?</h2>
          <p>
            You must begin to explain what the new opportunity is. Remember, if your idea is not unique, it's useless.
            By idea I mean the way the product will be introduced. It is the presentation of the product that is IDEA, not the product itself. Your product is the Idea of presenting something and this must be unique.
          </p>
        </div>
      </section>
</div>
        
{% endblock content %}

blog/templates/blog/words.html
{% extends "blog/blog_base.html" %}
{% load static %}

{% block content %}

<div class="container">



Words to use in your headlines, offers and calls to action.
Words about newness ( from https://www.copywritematters.com/copywriter-words-that-sell/ )
1. You

2. Because


3. Introducing

4. Welcome

5. Unique

6. Announcing

7. Breakthrough

8. Surprising

9. Exciting

10. Astounding

Words about exclusivity

11. Special

12. Secret

13. Hidden

14. Truth

15. Temptation

16. Forbidden

17. Never

18. Revealed

19. Exclusive

20. Limited

Words about urgency

21. Now

22. Discover

23. New

24. Results

25. Only

26. Direct

27. Hurry

28. Quick

29. Fast

Words that reassure

30. Can

31. Guarantee

32. Proven

33. Easy

34. Care

35. Simple

36. Safety

37. Lifetime

Words about caring

38. Family

39. Love

40. Children

41. Heaven

42. Dream

43. Health

Words about saving

44. Save

45. Money

46. Win

47. Cheap

48. Free

49. Reduced

50. Bargain

51. Bonus

52. Discount

53. Lowest

Words about pain

54. Hate

55. Failure

56. Afraid

57. Lazy

58. Humiliation

59. Alone

60. Reject

61. Stress

62. Stupid

63. Guilty

</div>

{% endblock content %}